# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Holger Schmeisky
email: mail@schmeisky.com
description: > # this means to ignore newlines until "baseurl:"
  This is a collection of stuff that I do and like in software, coding, research, science and everything else.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schmeisky.com" # the base hostname & protocol for your site
twitter_username: hschmeisky
github_username:  holger-s

# Build settings
markdown: kramdown
